baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'mac urbanists'
theme = 'etch'

[params]
    timeZone = "America/Chicago"

[menus]
[[menus.main]]
    name = 'about'
    pageRef = '/about'
    weight = 10
[[menus.main]]
    name = 'rondo'
    pageRef = '/rondo'
    weight = 20
[[menus.main]]
    name = 'tactics'
    pageRef = '/tactics'
    weight = 30
[[menus.main]]
    name = 'zoning'
    pageRef = '/zoning'
    weight = 30

[frontmatter]
  date = [':default']